name: Pull Translations from Lokalise

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise for login translations
        uses: lokalise/lokalise-pull-action@v3.14.0
        with:
          api_token: fb6ca3c2cbb968bba7bd69b8eb7bd28e257efd6c
          project_id: 9816395968b17983c7aa09.92256776
          async_mode: true
          translations_path: static/labels/json
          file_format: json
          base_lang: en
          file_ext: json
          flat_naming: true
          skip_include_tags: true
          override_branch_name: lokalise/translations-update-all
          additional_params: |
            --all-platforms
            --format=json
            --include-tags=login
            --original-filenames=false
            --bundle-structure=static/labels/json/login_%LANG_ISO%.%FORMAT%
          pr_body: |
            ## Translation Updates from Lokalise

            ### Review checklist:
            - [ ] Ensure translations changes correspond to pushed english strings
            - [ ] Update PR title with ticket number if assigned
            - [ ] Check for any formatting or encoding issues

            ---
            *This PR was automatically generated by the "Pull from Lokalise" workflow.*

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Pull from Lokalise for country translations
        uses: lokalise/lokalise-pull-action@v3.14.0
        with:
          api_token: fb6ca3c2cbb968bba7bd69b8eb7bd28e257efd6c
          project_id: 9816395968b17983c7aa09.92256776
          async_mode: true
          translations_path: static/labels/json
          file_format: json
          base_lang: en
          file_ext: json
          flat_naming: true
          skip_include_tags: true
          override_branch_name: lokalise/translations-update-all
          additional_params: |
            --all-platforms
            --format=json
            --include-tags=country
            --original-filenames=false
            --bundle-structure=static/labels/json/country_%LANG_ISO%.%FORMAT%
          pr_body: |
            ## Translation Updates from Lokalise

            ### Review checklist:
            - [ ] Ensure translations changes correspond to pushed english strings
            - [ ] Update PR title with ticket number if assigned
            - [ ] Check for any formatting or encoding issues

            ---
            *This PR was automatically generated by the "Pull from Lokalise" workflow.*
