name: Test Push to Lokalise
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v3.6.0
        with:
          api_token: db92319ee7d5a58062192edaf4ea2866fbf64daa
          project_id: 440878166791b5d76be464.89002884
          base_lang: en
          translations_path: |
            Locales/en/email.po
            Locales/en/notification.po
            Locales/en/forms.po
            Locales/en/common.po
            Locales/en/en.po
            Locales/en/auth.po
            Locales/en/navigation.po
            Locales/en/ecommerce.po
            Locales/en/dashboard.po
          file_format: po
          rambo_mode: true
