name: Test Push to Lokalise
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v3.8.1
        with:
          api_token: fb6ca3c2cbb968bba7bd69b8eb7bd28e257efd6c
          project_id: 45297207687e0592a89eb0.41949853
          base_lang: en
          translations_path: |
            Locales_2
          file_format: json
          flat_naming: true
          file_ext: json
          use_tag_tracking: true
          skip_default_flags: true
          rambo_mode: true
          additional_params: |
            --convert-placeholders
            --replace-modified
            --distinguish-by-file=false
            ${{ inputs.force && '--cleanup-mode' || '' }}
