name: Test Push to Lokalise
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List translation files
        run: |
          echo "Looking for files matching: Locales/en/*.po"
          ls -la Locales/en/*.po || echo "No .po files found!"

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v3.6.0
        with:
          api_token: db92319ee7d5a58062192edaf4ea2866fbf64daa
          project_id: 7324349368679d64e90596.42179787
          base_lang: en
          translations_path: |
            Locales
          file_format: po
          rambo_mode: true
          additional_params: "--include-path, --replace-modified"
